# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c75c417775917a0f7c0a037e73ec1ffeb6fa99ef9c459b315368c4d35637223ed123b60453e3923513d2077962a8b5d8cedd674ac854b6a4437915f51e98ef7

test:
  secret_key_base: a008a40d9d7d3018302c32c65fb8a23dd2e8262d3e2e39d8ac06ddd72f746f2864bdc1d74616714be5be6f434c3fecd031b8aa2fea9fdcf79ed58778845745ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
